# **FDA Drug Shortage Data v3**

Run on Python 3.14 | No Errors | No Warnings

Drug Shortage Home Page: https://www.fda.gov/drugs/drug-safety-and-availability/drug-shortages

Retrieves current drug shortage data directly from the FDA Drug Shortages API and stores it in a local SQLite database. Compares incoming records with existing entries and updates only rows where values have changed, keeping the database current while minimizing redundant processing.

In [1]:
# Import packages

# For data manipulation
import pandas as pd

# For working with SQLite databases
import sqlite3

# for working with JSON data
import json

# For making HTTP requests and handling responses
import requests as req

In [2]:
# Load the SQL Magic extension
%load_ext sql

In [3]:
# Set SQL Magic options
%config SqlMagic.named_parameters = "enabled"
%config SqlMagic.feedback = False

In [4]:
# Create connection to the SQLite database
%sql sqlite:///DrugShortage.db

In [5]:
# Connect to the website and download the json file

# URL of the json file
url = 'https://api.fda.gov/drug/shortages.json?search=generic_name:"tirzepatide", "semaglutide", "dulaglutide", "liraglutide", "exenatide"&limit=100'

# Set headers to mimic a browser request
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# Send a GET request
response = req.get(url, headers=headers)

# Check if the request was successful
if response.status_code == 200:
    # Parse the JSON content
    data = response.json()
    # Normalize the JSON data to a flat table
    if 'results' in data:
        df0 = pd.json_normalize(data['results'])
        print(df0.head())  # Display the first few rows
    else:
        print("No 'results' key found in the JSON response.")
else: # If the request was unsuccessful
    print(f"Failed to retrieve the json file. Status code: {response.status_code}")

  update_type initial_posting_date   package_ndc           generic_name  \
0  Reverified           07/18/2023  0169-2800-15  Liraglutide Injection
1  Reverified           07/18/2023  71288-563-84  Liraglutide Injection
2  Reverified           07/18/2023  0169-4060-13  Liraglutide Injection
3  Reverified           07/18/2023  71288-563-85  Liraglutide Injection
4  Reverified           07/18/2023  0169-4060-12  Liraglutide Injection

   contact_info          availability update_date        therapeutic_category  \
0  833-493-4689             Available  02/01/2026  [Endocrinology/Metabolism]
1  844-824-8426             Available  08/19/2025  [Endocrinology/Metabolism]
2  833-493-4689  Limited Availability  02/01/2026  [Endocrinology/Metabolism]
3  844-824-8426             Available  08/19/2025  [Endocrinology/Metabolism]
4  833-493-4689  Limited Availability  02/01/2026  [Endocrinology/Metabolism]

  dosage_form                                       presentation  ...  \
0   Injection   Saxenda, Injection, 6 mg/1 mL (NDC 0169-2800-15)  ...
1   Injection  Liraglutide, Injection, 6 mg/1 mL (NDC 71288-5...  ...
2   Injection   Victoza, Injection, 6 mg/1 mL (NDC 0169-4060-13)  ...
3   Injection  Liraglutide, Injection, 6 mg/1 mL (NDC 71288-5...  ...
4   Injection   Victoza, Injection, 6 mg/1 mL (NDC 0169-4060-12)  ...

                           openfda.spl_id  \
0  [49c3d82d-a708-46b2-a273-6ea032afa5c3]
1  [c4f6adef-1b2a-4e7c-b7a9-b19d4ed1df36]
2  [0d10d10e-0fe0-47ee-b9da-628e34907e98]
3  [c4f6adef-1b2a-4e7c-b7a9-b19d4ed1df36]
4  [0d10d10e-0fe0-47ee-b9da-628e34907e98]

                       openfda.spl_set_id  \
0  [3946d389-0926-4f77-a708-0acb8153b143]
1  [0efc3a89-211a-4496-baab-e8265e07de2b]
2  [5a9ef4ea-c76a-4d34-a604-27c5b505f5a4]
3  [0efc3a89-211a-4496-baab-e8265e07de2b]
4  [5a9ef4ea-c76a-4d34-a604-27c5b505f5a4]

                                 openfda.package_ndc  \
0         [0169-2800-15, 0169-2800-90, 0169-2800-97]
1                       [71288-563-84, 71288-563-85]
2  [0169-4060-13, 0169-4060-12, 0169-4060-90, 016...
3                       [71288-563-84, 71288-563-85]
4  [0169-4060-13, 0169-4060-12, 0169-4060-90, 016...

                            openfda.nui         openfda.pharm_class_epc  \
0  [N0000178480, M0160181, N0000020058]  [GLP-1 Receptor Agonist [EPC]]
1  [N0000178480, M0160181, N0000020058]  [GLP-1 Receptor Agonist [EPC]]
2  [N0000178480, M0160181, N0000020058]  [GLP-1 Receptor Agonist [EPC]]
3  [N0000178480, M0160181, N0000020058]  [GLP-1 Receptor Agonist [EPC]]
4  [N0000178480, M0160181, N0000020058]  [GLP-1 Receptor Agonist [EPC]]

           openfda.pharm_class_cs  \
0  [Glucagon-Like Peptide 1 [CS]]
1  [Glucagon-Like Peptide 1 [CS]]
2  [Glucagon-Like Peptide 1 [CS]]
3  [Glucagon-Like Peptide 1 [CS]]
4  [Glucagon-Like Peptide 1 [CS]]

                            openfda.pharm_class_moa  openfda.unii  \
0  [Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]]  [839I73S42A]
1  [Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]]  [839I73S42A]
2  [Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]]  [839I73S42A]
3  [Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]]  [839I73S42A]
4  [Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]]  [839I73S42A]

                      related_info                shortage_reason
0                              NaN                            NaN
1                              NaN                            NaN
2  Estimated shortage duration TBD  Delay in shipping of the drug
3                              NaN                            NaN
4  Estimated shortage duration TBD  Delay in shipping of the drug

[5 rows x 31 columns]

In [6]:
# Display the first 5 rows of the dataframe
df0.head()

,update_type,initial_posting_date,package_ndc,generic_name,contact_info,availability,update_date,therapeutic_category,dosage_form,presentation,...,openfda.spl_id,openfda.spl_set_id,openfda.package_ndc,openfda.nui,openfda.pharm_class_epc,openfda.pharm_class_cs,openfda.pharm_class_moa,openfda.unii,related_info,shortage_reason
0,Reverified,07/18/2023,0169-2800-15,Liraglutide Injection,833-493-4689,Available,02/01/2026,[Endocrinology/Metabolism],Injection,"Saxenda, Injection, 6 mg/1 mL (NDC 0169-2800-15)",...,[49c3d82d-a708-46b2-a273-6ea032afa5c3],[3946d389-0926-4f77-a708-0acb8153b143],"[0169-2800-15, 0169-2800-90, 0169-2800-97]","[N0000178480, M0160181, N0000020058]",[GLP-1 Receptor Agonist [EPC]],[Glucagon-Like Peptide 1 [CS]],[Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]],[839I73S42A],NaN,NaN
1,Reverified,07/18/2023,71288-563-84,Liraglutide Injection,844-824-8426,Available,08/19/2025,[Endocrinology/Metabolism],Injection,"Liraglutide, Injection, 6 mg/1 mL (NDC 71288-5...",...,[c4f6adef-1b2a-4e7c-b7a9-b19d4ed1df36],[0efc3a89-211a-4496-baab-e8265e07de2b],"[71288-563-84, 71288-563-85]","[N0000178480, M0160181, N0000020058]",[GLP-1 Receptor Agonist [EPC]],[Glucagon-Like Peptide 1 [CS]],[Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]],[839I73S42A],NaN,NaN
2,Reverified,07/18/2023,0169-4060-13,Liraglutide Injection,833-493-4689,Limited Availability,02/01/2026,[Endocrinology/Metabolism],Injection,"Victoza, Injection, 6 mg/1 mL (NDC 0169-4060-13)",...,[0d10d10e-0fe0-47ee-b9da-628e34907e98],[5a9ef4ea-c76a-4d34-a604-27c5b505f5a4],"[0169-4060-13, 0169-4060-12, 0169-4060-90, 016...","[N0000178480, M0160181, N0000020058]",[GLP-1 Receptor Agonist [EPC]],[Glucagon-Like Peptide 1 [CS]],[Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]],[839I73S42A],Estimated shortage duration TBD,Delay in shipping of the drug
3,Reverified,07/18/2023,71288-563-85,Liraglutide Injection,844-824-8426,Available,08/19/2025,[Endocrinology/Metabolism],Injection,"Liraglutide, Injection, 6 mg/1 mL (NDC 71288-5...",...,[c4f6adef-1b2a-4e7c-b7a9-b19d4ed1df36],[0efc3a89-211a-4496-baab-e8265e07de2b],"[71288-563-84, 71288-563-85]","[N0000178480, M0160181, N0000020058]",[GLP-1 Receptor Agonist [EPC]],[Glucagon-Like Peptide 1 [CS]],[Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]],[839I73S42A],NaN,NaN
4,Reverified,07/18/2023,0169-4060-12,Liraglutide Injection,833-493-4689,Limited Availability,02/01/2026,[Endocrinology/Metabolism],Injection,"Victoza, Injection, 6 mg/1 mL (NDC 0169-4060-12)",...,[0d10d10e-0fe0-47ee-b9da-628e34907e98],[5a9ef4ea-c76a-4d34-a604-27c5b505f5a4],"[0169-4060-13, 0169-4060-12, 0169-4060-90, 016...","[N0000178480, M0160181, N0000020058]",[GLP-1 Receptor Agonist [EPC]],[Glucagon-Like Peptide 1 [CS]],[Glucagon-like Peptide-1 (GLP-1) Agonists [MoA]],[839I73S42A],Estimated shortage duration TBD,Delay in shipping of the drug

In [7]:
# Keep only the relevant columns
df0 = df0[['update_type', 'generic_name', 'update_date', 'presentation', 'company_name', 'status', 'availability', 'related_info', 'shortage_reason']]

In [8]:
# Rename the columns
df0.rename(columns={
    'update_type': 'Type of Update',
    'generic_name': 'Generic Name',
    'update_date': 'Date of Update',
    'presentation': 'Presentation',
    'company_name': 'Company Name',
    'status': 'Status',
    'availability': 'Availability Information',
    'related_info': 'Related Information',
    'shortage_reason': 'Reason for Shortage'
}, inplace=True)

In [9]:
# Reorder the columns
df0 = df0[['Generic Name', 'Company Name', 'Presentation', 'Type of Update', 'Date of Update', 'Availability Information', 'Related Information', 'Reason for Shortage', 'Status']]

In [10]:
# Verify the data types of the columns
df0.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Generic Name              9 non-null      str
 1   Company Name              9 non-null      str
 2   Presentation              9 non-null      str
 3   Type of Update            9 non-null      str
 4   Date of Update            9 non-null      str
 5   Availability Information  9 non-null      str
 6   Related Information       6 non-null      str
 7   Reason for Shortage       2 non-null      str
 8   Status                    9 non-null      str
dtypes: str(9)
memory usage: 780.0 bytes

In [11]:
# Clean the data

# Replace the company names with shorter names
df0['Company Name'] = df0['Company Name'].replace({'Eli Lilly and Co.': 'Eli Lilly', 'Novo Nordisk, Inc.': 'Novo Nordisk', 'AstraZeneca AB': 'AstraZeneca'})

# Remove the word 'Injection' from the Generic Name column
df0['Generic Name'] = df0['Generic Name'].str.replace(' Injection', '')

# Split the Presentation column into three new columns: Brand Name, Administration, and Dosage
def split_presentation(pres):
    pres = pres.strip()
    parts = pres.split(',', maxsplit=2)
    if pres.startswith('Injection'):
        # Generic version
        brand_name = 'Liraglutide'
        administration = parts[0].strip()
        dosage = parts[1].strip() if len(parts) > 1 else ''
    else:
        # Brand-name version
        brand_name = parts[0].strip()
        administration = parts[1].strip() if len(parts) > 1 else ''
        dosage = parts[2].strip() if len(parts) > 2 else ''
    return pd.Series([brand_name, administration, dosage], index=['Brand Name', 'Administration', 'Dosage'])

# Apply the function to the dataframe
df0[['Brand Name', 'Administration', 'Dosage']] = df0['Presentation'].apply(split_presentation)

# Trim leading and trailing spaces from the new columns
df0['Brand Name'] = df0['Brand Name'].str.strip()
df0['Administration'] = df0['Administration'].str.strip()
df0['Dosage'] = df0['Dosage'].str.strip()

In [12]:
# Delete the Presentation column as it's no longer needed
df0.drop('Presentation', axis=1, inplace=True)

In [13]:
# Verify the changes
df0.head()

,Generic Name,Company Name,Type of Update,Date of Update,Availability Information,Related Information,Reason for Shortage,Status,Brand Name,Administration,Dosage
0,Liraglutide,Novo Nordisk,Reverified,02/01/2026,Available,NaN,NaN,Current,Saxenda,Injection,6 mg/1 mL (NDC 0169-2800-15)
1,Liraglutide,"Meitheal Pharmaceuticals, Inc.",Reverified,08/19/2025,Available,NaN,NaN,Current,Liraglutide,Injection,6 mg/1 mL (NDC 71288-563-84)
2,Liraglutide,Novo Nordisk,Reverified,02/01/2026,Limited Availability,Estimated shortage duration TBD,Delay in shipping of the drug,Current,Victoza,Injection,6 mg/1 mL (NDC 0169-4060-13)
3,Liraglutide,"Meitheal Pharmaceuticals, Inc.",Reverified,08/19/2025,Available,NaN,NaN,Current,Liraglutide,Injection,6 mg/1 mL (NDC 71288-563-85)
4,Liraglutide,Novo Nordisk,Reverified,02/01/2026,Limited Availability,Estimated shortage duration TBD,Delay in shipping of the drug,Current,Victoza,Injection,6 mg/1 mL (NDC 0169-4060-12)

In [14]:
# Further clean the data

# Drop ending period from Availibility Information column, if any values end with a period
df0['Availability Information'] = df0['Availability Information'].str.rstrip('.')

# Replace Currently avaliable with Available
df0['Availability Information'] = df0['Availability Information'].replace('Currently available', 'Available')

# If Status contains Discontinued, replace Availability Information with Discontinued
df0.loc[df0['Status'].str.contains('Discontinued'), 'Availability Information'] = 'Discontinued'

# If Administration is 'Injectable Suspension' replace with 'Injection'
df0.loc[df0['Administration'] == 'Injectable Suspension', 'Administration'] = 'Injection'

# If brand Name is Bydureon BCise or Byetta, replace Generic Name with Exenatide
df0.loc[df0['Brand Name'].str.contains('Bydureon BCise|Byetta'), 'Generic Name'] = 'Exenatide'

# Drop ending period from Related Information column, if any values end with a period
df0['Related Information'] = df0['Related Information'].str.rstrip('.')

# If Status is Resolved, replace Availability Information with Resolved
df0.loc[df0['Status'] == 'Resolved', 'Availability Information'] = 'Resolved'

# If Availability Information is Available or Resolved and Related Information is blank, replace Related Information with custom text
df0.loc[(df0['Availability Information'] == 'Available') & (df0['Related Information'].isnull()), 'Related Information'] = 'Quantity limits may apply'

df0.loc[(df0['Availability Information'] == 'Resolved') & (df0['Related Information'].isnull()), 'Related Information'] = 'Availability may vary'

# Replace entries ending with TBD with Shortage duration TBD
df0['Availability Information'] = df0['Availability Information'].replace('Limited availability.  Estimated shortage duration TBD', 'Shortage duration TBD')

# Create a new column called Dose, which is the Dosage column with everything after mg removed
df0['Dose'] = df0['Dosage'].str.split(' mg').str[0] + ' mg'

# Remove the last 3 characters from the Dose column
df0['Dose'] = df0['Dose'].str[:-3]

# If Brand Name is Bydureon BCise, replace Dose with 2
df0.loc[df0['Brand Name'] == 'Bydureon BCise', 'Dose'] = '2'

# If Brand Name is Byetta, replace Dose with first three characters of Dosage
df0.loc[df0['Brand Name'] == 'Byetta', 'Dose'] = df0['Dosage'].str[:3]

# If Brand Name is Bydureon BCise, Delete 'Extended Release, ' from the value in the Dosage column
df0.loc[df0['Brand Name'] == 'Bydureon BCise', 'Dosage'] = df0['Dosage'].str.replace('Extended Release, ', '')

# If Brand Name is Byetta, delete '(250MCG/ML) ' from the value in the Dosage column
df0.loc[df0['Brand Name'] == 'Byetta', 'Dosage'] = df0['Dosage'].str.replace('(250MCG/ML) ', '')

# Convert the Dose column to numeric and replace any errors with NaN to make it easier to work with 
df0['Dose'] = pd.to_numeric(df0['Dose'], errors='coerce')

# If Company Name is AstraZeneca and Availibility Information is NaN, replace Related Information with 'Please select an alternative GLP-1 product'
df0.loc[(df0['Company Name'] == 'AstraZeneca') & (df0['Related Information'].isnull()), 'Related Information'] = 'No longer available'

In [15]:
# Convert 'Date of Update' to datetime format
df0["Date of Update"] = pd.to_datetime(df0["Date of Update"])
df0["Date of Update"] = df0["Date of Update"].dt.strftime('%Y-%m-%d')

In [16]:
# Sort on Brand Name, Date of Update, and Dose
df0.sort_values(by=['Brand Name', 'Date of Update', 'Dose'], inplace=True)

In [17]:
# Reindex the dataframe to reflect the new order
df0.reset_index(drop=True, inplace=True)

In [18]:
# Reorder the columns
df0 = df0[['Brand Name', 'Generic Name', 'Company Name', 'Administration', 'Dosage', 'Dose', 'Type of Update', 'Date of Update', 'Availability Information', 'Related Information','Reason for Shortage']]

In [19]:
# Verify the changes
df0.head()

,Brand Name,Generic Name,Company Name,Administration,Dosage,Dose,Type of Update,Date of Update,Availability Information,Related Information,Reason for Shortage
0,Liraglutide,Liraglutide,"Meitheal Pharmaceuticals, Inc.",Injection,6 mg/1 mL (NDC 71288-563-84),6,Reverified,2025-08-19,Available,Quantity limits may apply,NaN
1,Liraglutide,Liraglutide,"Meitheal Pharmaceuticals, Inc.",Injection,6 mg/1 mL (NDC 71288-563-85),6,Reverified,2025-08-19,Available,Quantity limits may apply,NaN
2,Liraglutide,Liraglutide,"Hikma Pharmaceuticals USA, Inc.",Injection,6 mg/1 mL (NDC 0143-9144-02),6,Revised,2026-01-22,Available,Product will be made available as it is released,NaN
3,Liraglutide,Liraglutide,"Hikma Pharmaceuticals USA, Inc.",Injection,6 mg/1 mL (NDC 0143-9144-03),6,Revised,2026-01-22,Available,Product will be made available as it is released,NaN
4,Liraglutide,Liraglutide,Novo Nordisk,Injection,6 mg/1 mL (NDC 0480-3667-22),6,Reverified,2026-02-01,Available,Distributed by Teva,NaN

In [20]:
# Determine if there are any updates or new additions (inserts) to the database

# Initialize counters and lists for updates and inserts
updates = 0
inserts = 0
updated_rows = []
inserted_rows = []

# Iterate through the cleaned dataset and prepare variables
for _, row in df0.iterrows():
    dosage = row["Dosage"]
    new_date = row["Date of Update"]

    brand = row["Brand Name"]
    generic = row["Generic Name"]
    company = row["Company Name"]
    admin = row["Administration"]
    dose = row["Dose"]
    update_type = row["Type of Update"]
    avail = row["Availability Information"]
    related = row["Related Information"]
    reason = row["Reason for Shortage"]

    # Check if Dosage already exists
    result = %sql SELECT [Date of Update] FROM SHORTAGE_DATA WHERE Dosage = :dosage

    if result and result[0][0]:  # Existing row found
        existing_date = pd.to_datetime(result[0][0])
        if pd.to_datetime(new_date) > existing_date:
            _ = %sql UPDATE SHORTAGE_DATA SET \
                [Brand Name]=:brand, [Generic Name]=:generic, [Company Name]=:company, Administration=:admin, \
                Dose=:dose, [Type of Update]=:update_type, [Date of Update]=:new_date, \
                [Availability Information]=:avail, [Related Information]=:related, [Reason for Shortage]=:reason \
                WHERE Dosage=:dosage
            updates += 1
            updated_rows.append((dosage, new_date))
    else:
        _ = %sql INSERT INTO SHORTAGE_DATA (\
            [Brand Name], [Generic Name], [Company Name], Administration, Dosage, \
            Dose, [Type of Update], [Date of Update], [Availability Information], \
            [Related Information], [Reason for Shortage]) VALUES (\
            :brand, :generic, :company, :admin, :dosage, :dose, :update_type, :new_date, \
            :avail, :related, :reason)
        inserts += 1
        inserted_rows.append((dosage, new_date))

In [21]:
# Display counts of updates and inserts
print(f"Updated rows: {updates}")
print(f"Inserted rows: {inserts}")

Updated rows: 5
Inserted rows: 0

In [22]:
# Display updated and inserted rows
if updated_rows:
    print("\n--- Updated Rows ---")
    for dosage, date in updated_rows:
        print(f"Updated: {dosage} → {date}")

if inserted_rows:
    print("\n--- Inserted Rows ---")
    for dosage, date in inserted_rows:
        print(f"Inserted: {dosage} → {date}")

--- Updated Rows ---
Updated: 6 mg/1 mL (NDC 0480-3667-22) → 2026-02-01
Updated: 6 mg/1 mL (NDC 0480-3667-20) → 2026-02-01
Updated: 6 mg/1 mL (NDC 0169-2800-15) → 2026-02-01
Updated: 6 mg/1 mL (NDC 0169-4060-13) → 2026-02-01
Updated: 6 mg/1 mL (NDC 0169-4060-12) → 2026-02-01

In [23]:
%%sql
-- Convert the 'Date of Update' column to the format YYYY-MM-DD
UPDATE SHORTAGE_DATA
SET [Date of Update] = 
    substr([Date of Update], 7, 4) || '-' || 
    substr([Date of Update], 1, 2) || '-' || 
    substr([Date of Update], 4, 2)
WHERE length([Date of Update]) = 10 AND instr([Date of Update], '/') > 0;

++
||
++
++

In [24]:
%%sql
-- Find the total count of duplicate rows in the SHORTAGE_DATA table
SELECT SUM(duplicate_count - 1) AS total_duplicates
FROM (
    SELECT COUNT(*) AS duplicate_count
    FROM SHORTAGE_DATA
    GROUP BY "Brand Name", "Generic Name", "Company Name", "Administration", "Dosage", "Dose", "Type of Update", "Date of Update", "Availability Information", "Related Information", "Reason for Shortage"
    HAVING COUNT(*) > 1
) as duplicates;

+------------------+
| total_duplicates |
+------------------+
|       None       |
+------------------+

In [25]:
%%sql
-- Delete duplicate rows in the SHORTAGE_DATA table
DELETE FROM SHORTAGE_DATA
WHERE rowid NOT IN (
    SELECT MIN(rowid)
    FROM SHORTAGE_DATA
    GROUP BY "Brand Name", "Generic Name", "Company Name", "Administration", "Dosage", "Dose", "Type of Update", "Date of Update", "Availability Information", "Related Information", "Reason for Shortage"
);

++
||
++
++

In [26]:
# Display the first 5 rows of the SHORTAGE_DATA table
%sql SELECT * FROM SHORTAGE_DATA LIMIT 5

+----------------+--------------+---------------------------------+----------------+---------------------------------+-------+----------------+----------------+--------------------------+--------------------------------------------------+---------------------+
|   Brand Name   | Generic Name |           Company Name          | Administration |              Dosage             |  Dose | Type of Update | Date of Update | Availability Information |               Related Information                | Reason for Shortage |
+----------------+--------------+---------------------------------+----------------+---------------------------------+-------+----------------+----------------+--------------------------+--------------------------------------------------+---------------------+
| Bydureon BCise |  Exenatide   |           AstraZeneca           |   Injection    |  2 mg/.85 mL (NDC 0310-6540-04) |  2.0  |      New       |   2024-10-28   |       Discontinued       |               No longer available                |         None        |
|     Byetta     |  Exenatide   |           AstraZeneca           |   Injection    | 300MCG/1.2ML (NDC 0310-6512-01) | 300.0 |      New       |   2024-10-25   |       Discontinued       |               No longer available                |         None        |
|     Byetta     |  Exenatide   |           AstraZeneca           |   Injection    | 600MCG/2.4ML (NDC 0310-6524-01) | 600.0 |      New       |   2024-10-25   |       Discontinued       |               No longer available                |         None        |
|  Liraglutide   | Liraglutide  | Hikma Pharmaceuticals USA, Inc. |   Injection    |   6 mg/1 mL (NDC 0143-9144-03)  |  6.0  |    Revised     |   2026-01-22   |        Available         | Product will be made available as it is released |         None        |
|  Liraglutide   | Liraglutide  | Hikma Pharmaceuticals USA, Inc. |   Injection    |   6 mg/1 mL (NDC 0143-9144-02)  |  6.0  |    Revised     |   2026-01-22   |        Available         | Product will be made available as it is released |         None        |
+----------------+--------------+---------------------------------+----------------+---------------------------------+-------+----------------+----------------+--------------------------+--------------------------------------------------+---------------------+

In [27]:
# Retrieve all data from the SHORTAGE_DATA table
df = %sql SELECT * FROM SHORTAGE_DATA

# Convert the ResultSet to a DataFrame
df1 = df.DataFrame()

In [28]:
# Display the first 5 rows of the dataframe (df1)
df1.head()

,Brand Name,Generic Name,Company Name,Administration,Dosage,Dose,Type of Update,Date of Update,Availability Information,Related Information,Reason for Shortage
0,Bydureon BCise,Exenatide,AstraZeneca,Injection,2 mg/.85 mL (NDC 0310-6540-04),2.0,New,2024-10-28,Discontinued,No longer available,NaN
1,Byetta,Exenatide,AstraZeneca,Injection,300MCG/1.2ML (NDC 0310-6512-01),300.0,New,2024-10-25,Discontinued,No longer available,NaN
2,Byetta,Exenatide,AstraZeneca,Injection,600MCG/2.4ML (NDC 0310-6524-01),600.0,New,2024-10-25,Discontinued,No longer available,NaN
3,Liraglutide,Liraglutide,"Hikma Pharmaceuticals USA, Inc.",Injection,6 mg/1 mL (NDC 0143-9144-03),6.0,Revised,2026-01-22,Available,Product will be made available as it is released,NaN
4,Liraglutide,Liraglutide,"Hikma Pharmaceuticals USA, Inc.",Injection,6 mg/1 mL (NDC 0143-9144-02),6.0,Revised,2026-01-22,Available,Product will be made available as it is released,NaN

In [29]:
# Display basic information about the data
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Brand Name                36 non-null     str
 1   Generic Name              36 non-null     str
 2   Company Name              36 non-null     str
 3   Administration            36 non-null     str
 4   Dosage                    36 non-null     str
 5   Dose                      36 non-null     float64
 6   Type of Update            36 non-null     str
 7   Date of Update            36 non-null     str
 8   Availability Information  36 non-null     str
 9   Related Information       36 non-null     str
 10  Reason for Shortage       2 non-null      str
dtypes: float64(1), str(10)
memory usage: 3.2 KB

In [30]:
# Write the cleaned data to a CSV file without the index
df1.to_csv('Drugshortages_cleaned.csv', index=False)